# Generated by Django 3.0.3 on 2020-02-10 09:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('python', 'PYTHON'), ('django', 'DJANGO'), ('UI', 'UI'), ('Rest Api', 'REST API')], max_length=100)),
                ('trainers', multiselectfield.db.fields.MultiSelectField(choices=[('narayana', 'NARAYANA'), ('Srinivas', 'SRINIVAS'), ('mohan reddy', 'MOHAN REDDY'), ('wilson', 'WILSON')], max_length=100)),
                ('shift', multiselectfield.db.fields.MultiSelectField(choices=[('Morning', 'MORNING'), ('evening', 'EVENING'), ('nigth', 'NIGTH')], max_length=100)),
                ('location', multiselectfield.db.fields.MultiSelectField(choices=[('ameerpet', 'AMEERPET'), ('madhapur', 'MADHAPUR'), ('KPHB', 'KPHB')], max_length=100)),
                ('start_date', models.DateField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
